### ISSUE TITLE
Update NetbeePos

### ISSUE THREAD

**Issue by Moein-dev** [netbee-online/NetbeePosSampleKotlin#1]
سلام وقت بخیر
ما برای پوز کیوسک ها ip و port دستگاه پوز رو از سمت سرور دریافت میکنیم و نیاز داریم که اپلیکیشن پوز این دو مقدار رو بصورت ورودی از سمت اپلیکیشن ما دریافت کنه

**Comment by habibi-dev** [comment]
سلام 
چنین امکانی در حال حاضر امکان پذیر نمیباشد.
